[target.aarch64-linux-android]
ar = "/Users/yuanxiao/Documents/rust/gaoding-log-view-kit/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "/Users/yuanxiao/Documents/rust/gaoding-log-view-kit/NDK/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "/Users/yuanxiao/Documents/rust/gaoding-log-view-kit/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "/Users/yuanxiao/Documents/rust/gaoding-log-view-kit/NDK/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "/Users/yuanxiao/Documents/rust/gaoding-log-view-kit/NDK/x86/bin/i686-linux-android-ar"
linker = "/Users/yuanxiao/Documents/rust/gaoding-log-view-kit/NDK/x86/bin/i686-linux-android-clang"
